apiVersion: apps/v1
kind: Deployment
metadata:
  name: origoss
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: fenyvesimate211/origoss:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080